spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: first-api
          uri: lb://first-api
          predicates:
            - Path=/first-api
        - id: second-api
          uri: lb://second-api
          predicates:
            - Path=/second-api
  application:
    name: CLOUD-API-GATEWAY
server:
  port: 3333